package sitegroup

import (
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"

	"github.com/lmorchard/feedspool-go/internal/config"
	"github.com/sirupsen/logrus"
)

// ManifestName is the file, written in the output root, recording which site
// directories feedspool generated on the previous run.
const ManifestName = ".feedspool-sites.json"

// manifestVersion is the current on-disk manifest schema version.
const manifestVersion = 1

// manifestPerm is the file mode for the manifest.
const manifestPerm fs.FileMode = 0o600

// manifestTempPattern is the glob pattern used for the temp file WriteManifest
// writes before renaming it into place.
const manifestTempPattern = ManifestName + ".tmp-*"

// Manifest records the site directories generated by the previous run so the
// next run can prune the ones that disappeared.
type Manifest struct {
	Version int      `json:"version"`
	Slugs   []string `json:"slugs"`
}

// emptyManifest returns a manifest with no slugs, tagged with the current
// schema version. It is what ReadManifest yields whenever there is nothing
// safe to prune against: no file on disk, a corrupt file, or an unrecognized
// schema version.
func emptyManifest() *Manifest {
	return &Manifest{Version: manifestVersion}
}

// ReadManifest loads the manifest from outputDir. The manifest is derived
// bookkeeping, not source data, so any problem reading or interpreting it
// degrades to "there is nothing to prune" rather than a hard error: a missing
// file, a corrupt/truncated file, or an unrecognized schema version all yield
// an empty Manifest and a nil error. The only cost of that is a stale
// directory lingering an extra run, which is the safe direction for a
// deletion path.
func ReadManifest(outputDir string) (*Manifest, error) {
	path := filepath.Join(outputDir, ManifestName)
	data, err := os.ReadFile(path)
	if err != nil {
		if !errors.Is(err, fs.ErrNotExist) {
			logrus.Warnf("Ignoring %s: failed to read manifest: %v", ManifestName, err)
		}
		return emptyManifest(), nil
	}

	m := &Manifest{}
	if err := json.Unmarshal(data, m); err != nil {
		logrus.Warnf("Ignoring %s: failed to parse manifest: %v", ManifestName, err)
		return emptyManifest(), nil
	}

	if m.Version != manifestVersion {
		logrus.Warnf("Ignoring %s: unsupported manifest version %d (want %d)", ManifestName, m.Version, manifestVersion)
		return emptyManifest(), nil
	}

	return m, nil
}

// WriteManifest records the slugs of the given sites in outputDir.
//
// Callers that also prune stale directories must call Prune before
// WriteManifest: writing the new manifest first makes the "previous" and
// "current" slug sets identical, so a subsequent Prune silently removes
// nothing.
//
// The manifest is written to a temp file in outputDir and renamed into place,
// so a crash or full disk mid-write can never leave a partially written
// manifest for ReadManifest to trip over.
func WriteManifest(outputDir string, sites []Site) error {
	slugs := make([]string, 0, len(sites))
	for i := range sites {
		slugs = append(slugs, sites[i].Slug)
	}

	data, err := json.Marshal(&Manifest{Version: manifestVersion, Slugs: slugs})
	if err != nil {
		return fmt.Errorf("failed to encode %s: %w", ManifestName, err)
	}

	if err := os.MkdirAll(outputDir, config.DefaultDirPerm); err != nil {
		return fmt.Errorf("failed to create output directory %s: %w", outputDir, err)
	}

	tmp, err := os.CreateTemp(outputDir, manifestTempPattern)
	if err != nil {
		return fmt.Errorf("failed to create temp file for %s: %w", ManifestName, err)
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath) // Best-effort cleanup; irrelevant once the rename below succeeds.

	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("failed to write %s: %w", ManifestName, err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("failed to write %s: %w", ManifestName, err)
	}
	if err := os.Chmod(tmpPath, manifestPerm); err != nil {
		return fmt.Errorf("failed to set permissions on %s: %w", ManifestName, err)
	}

	if err := os.Rename(tmpPath, filepath.Join(outputDir, ManifestName)); err != nil {
		return fmt.Errorf("failed to write %s: %w", ManifestName, err)
	}
	return nil
}

// isSafeSlug reports whether slug names a direct child of an output directory.
// It rejects empty names, dot names, and anything containing a separator, so a
// hand-edited or corrupted manifest cannot make Prune escape the output root.
func isSafeSlug(slug string) bool {
	if slug == "" || slug == "." || slug == ".." {
		return false
	}
	return slug == filepath.Base(slug) && !filepath.IsAbs(slug)
}

// Prune removes site directories that the previous run generated but that are
// no longer discovered. It keys off discovered sites, not successfully
// rendered ones, so a site that failed to render is never deleted.
//
// A directory is removed only if it is named in the previous manifest and is
// a safe direct child of outputDir. Prune can therefore never escape the
// output root, but it does trust the manifest's contents: anyone who can
// write the manifest can name any direct child of outputDir for deletion.
//
// Callers must call Prune before WriteManifest: writing the new manifest
// first makes the "previous" and "current" slug sets identical, so a
// subsequent Prune silently removes nothing.
func Prune(outputDir string, sites []Site) (removed []string, err error) {
	previous, err := ReadManifest(outputDir)
	if err != nil {
		return nil, err
	}

	current := make(map[string]struct{}, len(sites))
	for i := range sites {
		current[sites[i].Slug] = struct{}{}
	}

	for _, slug := range previous.Slugs {
		if _, kept := current[slug]; kept {
			continue
		}
		if !isSafeSlug(slug) {
			continue
		}

		path := filepath.Join(outputDir, slug)
		// Lstat, not Stat: Stat follows symlinks, so a symlink pointing at a
		// directory outside outputDir would report IsDir() == true and be
		// handed to RemoveAll. Lstat reports the link itself, which is never
		// a directory, so symlinks are skipped regardless of their target.
		info, statErr := os.Lstat(path)
		if statErr != nil || !info.IsDir() {
			continue
		}
		if rmErr := os.RemoveAll(path); rmErr != nil {
			return removed, fmt.Errorf("failed to remove stale site directory %s: %w", path, rmErr)
		}
		removed = append(removed, slug)
	}

	return removed, nil
}
