package sitegroup

import (
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"

	"github.com/lmorchard/feedspool-go/internal/config"
)

// ManifestName is the file, written in the output root, recording which site
// directories feedspool generated on the previous run.
const ManifestName = ".feedspool-sites.json"

// manifestVersion is the current on-disk manifest schema version.
const manifestVersion = 1

// manifestPerm is the file mode for the manifest.
const manifestPerm fs.FileMode = 0o600

// Manifest records the site directories generated by the previous run so the
// next run can prune the ones that disappeared.
type Manifest struct {
	Version int      `json:"version"`
	Slugs   []string `json:"slugs"`
}

// ReadManifest loads the manifest from outputDir. A missing manifest is not an
// error: it yields an empty Manifest, meaning there is nothing to prune.
func ReadManifest(outputDir string) (*Manifest, error) {
	data, err := os.ReadFile(filepath.Join(outputDir, ManifestName))
	if errors.Is(err, fs.ErrNotExist) {
		return &Manifest{Version: manifestVersion}, nil
	}
	if err != nil {
		return nil, fmt.Errorf("failed to read %s: %w", ManifestName, err)
	}

	m := &Manifest{}
	if err := json.Unmarshal(data, m); err != nil {
		return nil, fmt.Errorf("failed to parse %s: %w", ManifestName, err)
	}
	return m, nil
}

// WriteManifest records the slugs of the given sites in outputDir.
func WriteManifest(outputDir string, sites []Site) error {
	slugs := make([]string, 0, len(sites))
	for i := range sites {
		slugs = append(slugs, sites[i].Slug)
	}

	data, err := json.Marshal(&Manifest{Version: manifestVersion, Slugs: slugs})
	if err != nil {
		return fmt.Errorf("failed to encode %s: %w", ManifestName, err)
	}

	if err := os.MkdirAll(outputDir, config.DefaultDirPerm); err != nil {
		return fmt.Errorf("failed to create output directory %s: %w", outputDir, err)
	}
	if err := os.WriteFile(filepath.Join(outputDir, ManifestName), data, manifestPerm); err != nil {
		return fmt.Errorf("failed to write %s: %w", ManifestName, err)
	}
	return nil
}

// isSafeSlug reports whether slug names a direct child of an output directory.
// It rejects empty names, dot names, and anything containing a separator, so a
// hand-edited or corrupted manifest cannot make Prune escape the output root.
func isSafeSlug(slug string) bool {
	if slug == "" || slug == "." || slug == ".." {
		return false
	}
	return slug == filepath.Base(slug) && !filepath.IsAbs(slug)
}

// Prune removes site directories that the previous run generated but that are
// no longer discovered. It keys off discovered sites, not successfully
// rendered ones, so a site that failed to render is never deleted.
//
// A directory is removed only if it is named in the previous manifest, is a
// safe direct child of outputDir, and exists as a directory. Prune can
// therefore never touch anything feedspool did not create.
func Prune(outputDir string, sites []Site) (removed []string, err error) {
	previous, err := ReadManifest(outputDir)
	if err != nil {
		return nil, err
	}

	current := make(map[string]struct{}, len(sites))
	for i := range sites {
		current[sites[i].Slug] = struct{}{}
	}

	for _, slug := range previous.Slugs {
		if _, kept := current[slug]; kept {
			continue
		}
		if !isSafeSlug(slug) {
			continue
		}

		path := filepath.Join(outputDir, slug)
		info, statErr := os.Stat(path)
		if statErr != nil || !info.IsDir() {
			continue
		}
		if rmErr := os.RemoveAll(path); rmErr != nil {
			return removed, fmt.Errorf("failed to remove stale site directory %s: %w", path, rmErr)
		}
		removed = append(removed, slug)
	}

	return removed, nil
}
