name: Build and Push Docker Image

# This workflow only builds and pushes Docker images after all CI checks pass

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    
  docker:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: lmorchard/feedspool
          tags: |
            # Latest tag for main branch
            type=raw,value=latest,enable={{is_default_branch}}
            # Version tag for releases (e.g., v1.2.3)
            type=ref,event=tag
          labels: |
            org.opencontainers.image.title=feedspool
            org.opencontainers.image.description=RSS/Atom feed aggregator and static site generator
            org.opencontainers.image.vendor=lmorchard

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64