name: Build and Push Docker Image

# This workflow builds Docker images using pre-built binaries from releases:
# - Rolling releases: Triggered after rolling release workflow completes
# - Tagged releases: Triggered after tagged release is published

on:
  workflow_run:
    workflows: ["Rolling Release", "Release"]
    types: [completed]

jobs:
  docker:
    # Only run if the upstream workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download release binary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Determine if this was triggered by Rolling Release or Release workflow
          if [ "${{ github.event.workflow_run.name }}" = "Rolling Release" ]; then
            # Download from latest rolling release
            PATTERN="feedspool_latest_linux_amd64.tar.gz"
            TAG="latest"
            echo "Triggered by Rolling Release - using latest tag"
          else
            # This was triggered by Release workflow, get the tag from the ref
            # The workflow_run event doesn't give us the tag directly, so we get the latest release
            TAG=$(gh release list --limit 1 --json tagName --jq '.[0].tagName')
            PATTERN="feedspool_${TAG}_linux_amd64.tar.gz"
            echo "Triggered by Release workflow - using tag ${TAG}"
          fi
          
          echo "Downloading binary for ${TAG} with pattern ${PATTERN}"
          gh release download "${TAG}" --pattern "${PATTERN}" --dir ./temp
          cd temp
          tar -xzf "${PATTERN}"
          mv feedspool ../
          cd ..
          rm -rf temp
          chmod +x feedspool
          
          # Verify the binary was downloaded and is executable
          echo "Binary verification:"
          ls -la feedspool
          file feedspool
          ./feedspool version || echo "Binary test failed"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: lmorchard/feedspool
          tags: |
            # Latest tag for main branch
            type=raw,value=latest,enable={{is_default_branch}}
            # Version tag for releases (e.g., v1.2.3)
            type=ref,event=tag
          labels: |
            org.opencontainers.image.title=feedspool
            org.opencontainers.image.description=RSS/Atom feed aggregator and static site generator
            org.opencontainers.image.vendor=lmorchard

      - name: Verify binary in build context
        run: |
          echo "Files in build context:"
          ls -la
          if [ ! -f feedspool ]; then
            echo "ERROR: feedspool binary not found in build context"
            exit 1
          fi
          echo "Binary verified in build context"

      - name: Build and push Docker image (from release binary)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.prebuilt
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64