name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  # Run CI checks first (lint, test) before building release
  ci:
    uses: ./.github/workflows/ci.yml

  build:
    name: Build
    needs: ci
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
          - os: ubuntu-latest  
            goos: linux
            goarch: arm64
          - os: macos-latest
            goos: darwin
            goarch: amd64
          - os: macos-latest
            goos: darwin
            goarch: arm64
          - os: windows-latest
            goos: windows
            goarch: amd64
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install cross-compilation dependencies (Linux)
      if: matrix.os == 'ubuntu-latest' && matrix.goarch == 'arm64'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu
        echo "CC=aarch64-linux-gnu-gcc" >> $GITHUB_ENV

    - name: Set version variables
      shell: bash
      run: |
        echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        echo "COMMIT=${GITHUB_SHA::7}" >> $GITHUB_ENV
        echo "DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV

    - name: Build binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 1
      shell: bash
      run: |
        output_name="feedspool"
        if [ "$GOOS" = "windows" ]; then
          output_name="feedspool.exe"
        fi
        
        go build \
          -ldflags "-X github.com/lmorchard/feedspool-go/cmd.Version=$VERSION -X github.com/lmorchard/feedspool-go/cmd.Commit=$COMMIT -X github.com/lmorchard/feedspool-go/cmd.Date=$DATE" \
          -o "$output_name" main.go

    - name: Create archive
      shell: bash
      run: |
        output_name="feedspool"
        if [ "$GOOS" = "windows" ]; then
          output_name="feedspool.exe"
        fi
        
        archive_name="feedspool_${VERSION}_${{ matrix.goos }}_${{ matrix.goarch }}"
        
        if [ "${{ matrix.goos }}" = "windows" ]; then
          zip "${archive_name}.zip" "$output_name"
          echo "ARCHIVE=${archive_name}.zip" >> $GITHUB_ENV
        else
          tar -czf "${archive_name}.tar.gz" "$output_name"
          echo "ARCHIVE=${archive_name}.tar.gz" >> $GITHUB_ENV
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARCHIVE }}
        path: ${{ env.ARCHIVE }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: dist
        merge-multiple: true

    - name: Generate checksums
      run: |
        cd dist
        sha256sum * > checksums.txt

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*
        generate_release_notes: true
        draft: false
        prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}